Add documentation for filtering on multiple health scores
q-m/q-m.github.io pull request #8
Opened 2017-03-06 10:44 UTC by martijnbleeker

2017-03-06 10:51 UTC, wvengen requested changes

2017-03-06 10:51 UTC, wvengen commented on api-docs/swagger-v1.1.yml
> +    required: false
I would put in the enum here. We may need to use a different way to accept array parameters (e.g. like [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object-example)), need to experiment with that if the client supports it.

2017-03-06 13:20 UTC, wvengen commented on api-docs/swagger-v1.1.yml
> +    collectionFormat: multi
Cool, curious to see how it looks in the UI :)

2017-03-06 13:22 UTC, martijnbleeker commented on api-docs/swagger-v1.1.yml
> +    collectionFormat: multi
I've tested it locally, it works. Not sure about the look though.

![screen shot 2017-03-06 at 14 22 13](https://cloud.githubusercontent.com/assets/445211/23611607/573f1726-0278-11e7-876e-1731ac9e122e.png)

2017-03-06 13:29 UTC, wvengen commented on api-docs/swagger-v1.1.yml
> +    collectionFormat: multi
Interesting, but that's it. I think we can omit the _, repeat parameter_ when using this :)

2017-03-06 13:57 UTC, wvengen commented on api-docs/swagger-v1.1.yml
> +    description: restrict by health scores
(and, naturally, the others too)

2017-03-07 09:48 UTC, wvengen approved these changes

2017-03-08 13:53 UTC, merged